import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const iconNames = [
  'alert-circle',
  'alert-triangle',
  'archive',
  'arrow-left',
  'arrow-right',
  'arrows-sort',
  'brand-android',
  'building',
  'calendar',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'circle-check',
  'circle-plus',
  'clipboard',
  'clock',
  'copy',
  'credit-card',
  'device-desktop',
  'device-mobile',
  'dots',
  'download',
  'edit',
  'external-link',
  'eye',
  'eye-off',
  'file',
  'file-description',
  'filter',
  'fingerprint',
  'folder',
  'folder-open',
  'folder-plus',
  'heart',
  'help-circle',
  'history',
  'home',
  'id',
  'info-circle',
  'key',
  'layout-sidebar-left-collapse',
  'layout-sidebar-left-expand',
  'link',
  'loader-2',
  'lock',
  'lock-open',
  'logout',
  'mail',
  'menu-2',
  'moon',
  'note',
  'paperclip',
  'password',
  'plus',
  'refresh',
  'restore',
  'search',
  'settings',
  'share',
  'shield',
  'shield-check',
  'shield-lock',
  'sparkles',
  'star',
  'sun',
  'trash',
  'upload',
  'user',
  'user-plus',
  'users',
  'wand',
  'world',
  'x',
];

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, '..');
const collectionPath = path.resolve(packageDir, '../..', 'node_modules/@iconify-json/tabler/icons.json');
const outputPath = path.resolve(packageDir, 'src/icons/generated.ts');
const collection = JSON.parse(await readFile(collectionPath, 'utf8'));

const missing = iconNames.filter((name) => !collection.icons[name]);
if (missing.length > 0) {
  throw new Error(`Missing Tabler icons: ${missing.join(', ')}`);
}

const entries = iconNames.map((name) => {
  const icon = collection.icons[name];
  const data = {
    body: icon.body,
    width: icon.width ?? collection.width ?? 24,
    height: icon.height ?? collection.height ?? 24,
  };
  return `  ${JSON.stringify(name)}: ${JSON.stringify(data)},`;
});

const source = `/* This file is generated by scripts/generate-icons.mjs. */\n` +
  `import type { IconifyIcon } from '@iconify/react';\n\n` +
  `export const lockboxIcons = {\n${entries.join('\n')}\n} as const satisfies Record<string, IconifyIcon>;\n\n` +
  `export type IconName = keyof typeof lockboxIcons;\n`;

await writeFile(outputPath, source);
