/**
 * Email alias routes — proxy to SimpleLogin / AnonAddy.
 * API keys are encrypted client-side; server only stores ciphertext.
 * For proxy calls, client decrypts locally and sends plaintext key in request body.
 */

import { Hono } from 'hono';
import { eq } from 'drizzle-orm';
import { createDb } from '../db/index.js';
import { aliasSettings } from '../db/schema.js';
import { authMiddleware } from '../middleware/auth.js';

const VALID_PROVIDERS = ['simplelogin', 'anonaddy'] as const;
type AliasProvider = (typeof VALID_PROVIDERS)[number];

type Bindings = { DB: D1Database };
type Variables = { userId: string };

export const aliasRoutes = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// All alias routes require authentication
aliasRoutes.use('*', authMiddleware);

// ─── PUT /api/settings/alias ────────────────────────────────────────────────
// Save/update alias provider configuration

aliasRoutes.put('/settings/alias', async (c) => {
  const userId = c.get('userId');
  const body = await c.req.json().catch(() => null);
  if (!body) return c.json({ error: 'Invalid JSON' }, 400);

  const { provider, encryptedApiKey, baseUrl } = body as Record<string, unknown>;

  if (!provider || typeof provider !== 'string') {
    return c.json({ error: 'Missing provider' }, 400);
  }
  if (!VALID_PROVIDERS.includes(provider as AliasProvider)) {
    return c.json({ error: 'Invalid provider. Must be simplelogin or anonaddy' }, 400);
  }
  if (!encryptedApiKey || typeof encryptedApiKey !== 'string') {
    return c.json({ error: 'Missing encryptedApiKey' }, 400);
  }

  const db = createDb(c.env.DB);

  // Upsert: try update first, insert if not exists
  const existing = await db
    .select()
    .from(aliasSettings)
    .where(eq(aliasSettings.userId, userId))
    .get();

  if (existing) {
    await db
      .update(aliasSettings)
      .set({
        provider: provider as string,
        encryptedApiKey: encryptedApiKey as string,
        baseUrl: (baseUrl as string) ?? null,
      })
      .where(eq(aliasSettings.userId, userId));
  } else {
    await db.insert(aliasSettings).values({
      userId,
      provider: provider as string,
      encryptedApiKey: encryptedApiKey as string,
      baseUrl: (baseUrl as string) ?? null,
    });
  }

  return c.json({ success: true });
});

// ─── GET /api/settings/alias ────────────────────────────────────────────────
// Get alias provider configuration for user

aliasRoutes.get('/settings/alias', async (c) => {
  const userId = c.get('userId');
  const db = createDb(c.env.DB);

  const config = await db
    .select()
    .from(aliasSettings)
    .where(eq(aliasSettings.userId, userId))
    .get();

  if (!config) {
    return c.json({ error: 'Alias provider not configured' }, 404);
  }

  return c.json({
    provider: config.provider,
    encryptedApiKey: config.encryptedApiKey,
    baseUrl: config.baseUrl,
  });
});

// ─── DELETE /api/settings/alias ─────────────────────────────────────────────
// Remove alias provider configuration

aliasRoutes.delete('/settings/alias', async (c) => {
  const userId = c.get('userId');
  const db = createDb(c.env.DB);

  const existing = await db
    .select()
    .from(aliasSettings)
    .where(eq(aliasSettings.userId, userId))
    .get();

  if (!existing) {
    return c.json({ error: 'Not found' }, 404);
  }

  await db.delete(aliasSettings).where(eq(aliasSettings.userId, userId));
  return c.json({ success: true });
});

// ─── POST /api/aliases/generate ─────────────────────────────────────────────
// Generate a new email alias. Client sends decrypted apiKey in body.

aliasRoutes.post('/aliases/generate', async (c) => {
  const body = await c.req.json().catch(() => null);
  if (!body) return c.json({ error: 'Invalid JSON' }, 400);

  const { provider, apiKey, baseUrl } = body as Record<string, unknown>;

  if (!provider || !VALID_PROVIDERS.includes(provider as AliasProvider)) {
    return c.json({ error: 'Invalid provider' }, 400);
  }
  if (!apiKey || typeof apiKey !== 'string') {
    return c.json({ error: 'Missing apiKey' }, 400);
  }

  try {
    let aliasEmail: string;

    if (provider === 'simplelogin') {
      const slBase = (baseUrl as string) || 'https://app.simplelogin.io';
      const res = await fetch(`${slBase}/api/alias/random/new`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authentication: apiKey,
        },
        body: JSON.stringify({ note: 'Generated by Lockbox' }),
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => 'Unknown error');
        return c.json({ error: `SimpleLogin error: ${errText}` }, 502);
      }

      const data = (await res.json()) as { alias?: string };
      aliasEmail = data.alias || '';
    } else {
      // anonaddy
      const adBase = (baseUrl as string) || 'https://app.anonaddy.com';
      const res = await fetch(`${adBase}/api/v1/aliases`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
          'X-Requested-With': 'XMLHttpRequest',
        },
        body: JSON.stringify({
          domain: 'anonaddy.me',
          description: 'Lockbox',
        }),
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => 'Unknown error');
        return c.json({ error: `AnonAddy error: ${errText}` }, 502);
      }

      const data = (await res.json()) as { data?: { email?: string } };
      aliasEmail = data.data?.email || '';
    }

    if (!aliasEmail) {
      return c.json({ error: 'Provider returned no alias' }, 502);
    }

    return c.json({ alias: { email: aliasEmail } });
  } catch (err) {
    return c.json({ error: 'Failed to contact alias provider' }, 502);
  }
});

// ─── GET /api/aliases ───────────────────────────────────────────────────────
// List aliases from provider. Client sends provider + apiKey in headers.

aliasRoutes.get('/aliases', async (c) => {
  const provider = c.req.header('X-Alias-Provider');
  const apiKey = c.req.header('X-Alias-ApiKey');
  const baseUrl = c.req.header('X-Alias-BaseUrl');

  if (!provider || !VALID_PROVIDERS.includes(provider as AliasProvider)) {
    return c.json({ error: 'Missing or invalid X-Alias-Provider header' }, 400);
  }
  if (!apiKey) {
    return c.json({ error: 'Missing X-Alias-ApiKey header' }, 400);
  }

  try {
    if (provider === 'simplelogin') {
      const slBase = baseUrl || 'https://app.simplelogin.io';
      const res = await fetch(`${slBase}/api/v2/aliases?page_id=0`, {
        headers: { Authentication: apiKey },
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => 'Unknown error');
        return c.json({ error: `SimpleLogin error: ${errText}` }, 502);
      }

      const data = (await res.json()) as {
        aliases?: Array<{ alias: string; enabled: boolean; id: number }>;
      };
      const aliases = (data.aliases || []).map((a) => ({
        email: a.alias,
        enabled: a.enabled,
        id: String(a.id),
      }));

      return c.json({ aliases });
    } else {
      // anonaddy
      const adBase = baseUrl || 'https://app.anonaddy.com';
      const res = await fetch(`${adBase}/api/v1/aliases`, {
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'X-Requested-With': 'XMLHttpRequest',
        },
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => 'Unknown error');
        return c.json({ error: `AnonAddy error: ${errText}` }, 502);
      }

      const data = (await res.json()) as {
        data?: Array<{ email: string; active: boolean; id: string }>;
      };
      const aliases = (data.data || []).map((a) => ({
        email: a.email,
        enabled: a.active,
        id: a.id,
      }));

      return c.json({ aliases });
    }
  } catch (err) {
    return c.json({ error: 'Failed to contact alias provider' }, 502);
  }
});
