name = "lockbox-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGINS = "https://lockbox-web.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "lockbox-vault"
database_id = "a62712d1-c9c6-4ebe-a805-fb6f1e69cb4a"
migrations_dir = "drizzle"

[durable_objects]
bindings = [{ name = "SYNC_HUB", class_name = "VaultSyncHub" }]

[[migrations]]
tag = "v1"
new_classes = ["VaultSyncHub"]

[[ratelimits]]
name = "AUTH_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 5
  period = 60


[triggers]
crons = ["0 2 * * *"]